micronaut:
  application:
    name: graphqlDemoApp
  security:
    enabled: true
    interceptUrlMap:
      - pattern: /graphiql
        access:
          - isAnonymous()
      - pattern: /graphql
        access:
          - isAuthenticated()

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    packages-to-scan:
      - 'com.micronaut.tutorial.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
